import org.slf4j.Logger
import org.slf4j.LoggerFactory;

/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'simon' at '12/11/15 12:21 AM' with Gradle 2.7
 *
 * @author simon, @date 12/11/15 12:21 AM
 */
class Library {
	private static Logger logger = LoggerFactory.getLogger(Library.class)
	
	boolean someLibraryMethod() {
		logger.info('running some method')
        true
    }
}
