/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vogella' at '12/8/15 5:59 PM' with Gradle 2.6
 *
 * @author vogella, @date 12/8/15 5:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
