/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'simon' at '12/10/15 12:29 AM' with Gradle 2.7
 *
 * @author simon, @date 12/10/15 12:29 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
