/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'simon' at '12/11/15 12:21 AM' with Gradle 2.7
 *
 * @author simon, @date 12/11/15 12:21 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
