/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'simon' at '12/9/15 7:45 PM' with Gradle 2.7
 *
 * @author simon, @date 12/9/15 7:45 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
